# Site Settings
title: "Jonathan's CV"
description: "Jonathan Perera - CV"
url: 'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Jonathan <br> <i>Perera </i>
tagline: Undergraduate Student
pic: Headshot.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Immunologist with a focus in unravelling the immune contribution to neurological disease by leveraging the advances in systems biology. Currently a PhD Candidate in the labs of Prof. John Sampson and Prof. Michael Gunn at Duke University (Durham, NC). 8 years of cross-disciplinary experience in the field of neuroimmunology has given me a unique perspective on the complex nature of the field.'

#sidebar links
email: jonathan.perera@duke.edu
phone: 
website: jonathanperera10.wixsite.com/jp-portfolio/
linkedin: jonathan-perera 
github: jperera1 
scholar: ----------------
orcid: 0000-0000-0000-0000 
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-113953128-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
