# Site Settings
title: "Jonathan's CV"
description: "Jonathan Perera - CV"
url: 'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Jonathan <br> <i>Perera </i>
tagline: Undergraduate Student
pic: Headshot.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Aspiring physician-scientist with a passion for exploring the neuroregenerative and protective capabilities of stem cell therapies through the lens of bioinformatics, cell biology, and immunotherapy. Currently an undergraduate student studying Biomedical Engineering at Duke University and working on completing research projects in-person and remotely at the Sampson Lab (Duke), Quinones Lab (Mayo Clinic), Lin Lab (Harvard-MIT). With both wet-lab and computational experience, I am uniquely placed to investigate the intricate field of neuropathology."

#sidebar links
email: jonathan.perera@duke.edu
phone: 
website: jonathanperera10.wixsite.com/jp-portfolio/
linkedin: jonathan-perera 
github: jperera1 
scholar: ----------------
orcid: 0000-0000-0000-0000 
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-113953128-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
